"""Add field for FOB price in Procurement, and default adjustment in Country.

Revision ID: 21231f247e8d
Revises: 4b83ac5e95ab
Create Date: 2014-11-28 14:05:02.955818

"""

# revision identifiers, used by Alembic.
revision = '21231f247e8d'
down_revision = '4b83ac5e95ab'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('country', sa.Column('default_fob_adjustment', sa.Float(), nullable=True))
    op.add_column('procurement', sa.Column('unit_price_usd_fob', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('procurement', 'unit_price_usd_fob')
    op.drop_column('country', 'default_fob_adjustment')
    ### end Alembic commands ###
