"""Add static models.

Revision ID: 3dbd6eee864d
Revises: 21231f247e8d
Create Date: 2014-12-11 09:17:04.631385

"""

# revision identifiers, used by Alembic.
revision = '3dbd6eee864d'
down_revision = '21231f247e8d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('important_link',
    sa.Column('important_link_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=256), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('important_link_id')
    )
    op.create_table('tender_schedule',
    sa.Column('tender_schedule_id', sa.Integer(), nullable=False),
    sa.Column('organisation', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=150), nullable=False),
    sa.Column('url', sa.String(length=256), nullable=True),
    sa.Column('start_date', sa.String(length=150), nullable=False),
    sa.Column('duration', sa.String(length=150), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.country_id'], deferrable=True),
    sa.PrimaryKeyConstraint('tender_schedule_id')
    )
    op.create_table('medicine_register',
    sa.Column('medicine_register_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=256), nullable=True),
    sa.Column('description', sa.String(length=150), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.country_id'], deferrable=True),
    sa.PrimaryKeyConstraint('medicine_register_id')
    )
    op.alter_column(u'country', 'default_fob_adjustment',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(u'country', 'default_fob_adjustment',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_table('medicine_register')
    op.drop_table('tender_schedule')
    op.drop_table('important_link')
    ### end Alembic commands ###
