"""Add indexes

Revision ID: 4b83ac5e95ab
Revises: 3f086b765016
Create Date: 2014-11-28 10:12:34.381562

"""

# revision identifiers, used by Alembic.
revision = '4b83ac5e95ab'
down_revision = '3f086b765016'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_procurement_country_id'), 'procurement', ['country_id'], unique=False)
    op.create_index(op.f('ix_procurement_product_id'), 'procurement', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_medicine_id'), 'product', ['medicine_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_medicine_id'), table_name='product')
    op.drop_index(op.f('ix_procurement_product_id'), table_name='procurement')
    op.drop_index(op.f('ix_procurement_country_id'), table_name='procurement')
    ### end Alembic commands ###
